Quick review and redact README

diff --git a/etc/versionCheck/depcheck b/etc/versionCheck/depcheck
--- a/etc/versionCheck/depcheck
+++ b/etc/versionCheck/depcheck
@@ -1,52 +1,66 @@
 export LC_ALL=C
 
-bashInstalled=`bash --version | head -n1 | cut -d" " -f2-4 | egrep -o "[0-9].{3}"`
-binutilsInstalled=`ld --version | head -n1 | cut -d" " -f3- | egrep -o "[0-9].{3}"`
-bisonInstalled=`bison --version | head -n1 |egrep -o "[0-9].{3,}"`
-bzip2Installed=`bzip2 --version 2>&1 < /dev/null | head -n1 | cut -d" " -f1,6- |egrep -o "[0-9].[0-9].[0-9]"`
-diffInstalled=`diff --version | head -n1 | egrep -o "[0-9].[0-9]"`
-findInstalled=`find --version | head -n1 | egrep -o "[0-9].{3,}"`
-gawkInstalled=`gawk --version | head -n1 | egrep -o "[0-9].[0-9].[0-9]" |head -n1`
-gccInstalled=`gcc --version | head -n1 | egrep -o "[0-9].[0-9].[0-9]"`
-glibcInstalled=`ldd --version | head -n1 | egrep -o "[0-9].[0-9][0-9]"`
-grepInstalled=`grep --version | head -n1 |egrep -o "[0-9].{2}"`
-gzipInstalled=`gzip --version | head -n1 | egrep -o "[0-9].{1,}"`
-m4Installed=`m4 --version | head -n1 | egrep -o "[0-9].[0-9].[0-9]{1,}"`
-makeInstalled=`make --version | head -n1 | egrep -o "[0-9].{1,}"`
-patchInstalled=`patch --version | head -n1 | egrep -o "[0-9].{3,}"`
-perlInstall=`perl -V:version | egrep -o "([0-9].{5})"`
-sedInstalled=`sed --version | head -n1| egrep -o "[0-9].{1,}"`
-tarInstalled=`tar --version | head -n1 |egrep -o "[0-9].{2,}"`
-makeinfoInstalled=`egrep -o "[0-9].[0-9]" < <(makeinfo --version | head -n1)`
-xzInstalled=`xz --version | head -n1 | egrep -o "[0-9].{4}"`
-coreutilsInstalled=`chown --version | head -n1 | cut -d")" -f2`
+declare -a reqList=('bash' 'ld' 'bison' 'bzip2' 'diff' 'find' 'gawk' 'gcc' 'g++' 'ldd' 'grep' 'gzip' 'm4' 'make' 'patch' 'perl' 'sed' 'tar' 'makeinfo' 'xz' 'chown')
+declare -a reqVer=('3.2' '2.25' '2.7' '1.0.4' '2.8.1' '4.2.31' '4.0.1' '4.9' '8.2.0' '2.11' '2.5.1a' '1.3.12' '1.4.10' '4.0' '2.5.4' '5.8.8' '4.1.5' '1.2.2' '4.7' '5.0.0' '6.9')
+declare -a missReq=()
+declare -a badVer=()
 
-declare -a reqList=('bash' 'ld' 'bison' 'bzip2' 'diff' 'find' 'gawk' 'gcc' 'ldd' 'grep' 'gzip' 'm4' 'make' 'patch' 'perl' 'sed' 'tar' 'makeinfo' 'xz' 'chown')
-declare -a reqVer=('3.2' '2.25' '2.7' '1.0.4' '2.8.1' '4.2.31' '4.0.1' '4.9' '2.11' '2.5.1a' '1.3.12' '1.4.10' '4.0' '2.5.4' '5.8.8' '4.1.5' '1.2.2' '4.7' '5.0.0' '6.9')
-declare -a reqInst=("${bashInstalled}" "${binutilsInstalled}" "${bisonInstalled}" "${bzip2Installed}" "${diffInstalled}" "${findInstalled}" "${gawkInstalled}" "${gccInstalled}" "${glibcInstalled}" "${grepInstalled}" "${gzipInstalled}" "${m4Installed}" "${makeInstalled}" "${patchInstalled}" "${perlInstall}" "${sedInstalled}" "${tarInstalled}" "${makeinfoInstalled}" "${xzInstalled}" "${coreutilsInstalled}")
 v=0
 reqLen=${#reqList[@]}
+allGood=0
 while [ $v -lt $reqLen ]; do
-    log "GEN|INFO|Checking if ${reqList[$v]} is installed." t
-    checkInstalled "${reqList[$v]}"
+    log "GEN|INFO|Checking if "${reqList[$v]}" is installed." t
+    checkInstalled ${reqList[$v]}
     if [[ $? > 0 ]]; then
-        log "GEN|ERROR|Could not find it." t
+        log "GEN|ERROR|"${reqList[$v]}" not found." t
+        missReq+=(${reqList[$v]})
+        allGood=1
+    fi
+    ((v++))
+done
+if [[ $allGood > 0 ]]; then
+    for r in ${missReq[@]}; do
+        log "GEN|ERROR|"$r" required and not found." t
+    done
+    log "GEN|FATAL|Requirement are not met, please fix before continuing." t
+    return 1
+fi
+
+v=0
+reqLen=${#reqList[@]}
+allGood=0
+
+while [ $v -lt $reqLen ]; do
+    ri=${reqList[$v]}
+    rv=${reqVer[$v]}
+    declare ver
+    log "GEN|INFO|Checking version of $ri" t
+    getVersion  $ri ver
+    log "GEN|INFO|Got: $ver"
+    vercomp $ver $rv
+    if [[ $? > 0 ]]; then
+        log "GEN|ERROR|${reqList[$v]}  version is no good, $rv needed." t
+        badVer+=($ri'=>'$ver',needed=>'$rv)
+        allGood=1
     else
-        log "GEN|INFO|Found it. Checking Version."
-        vercomp "${reqInst[$v]}" "${reqVer[$v]}"
-        if [[ $? > 0 ]]; then
-            log "GEN|ERROR|Error,${reqList[$v]}  version is no good, I found ${reqInst[$v]}, ${reqVer[$v]} needed." t
-        else
-            log "GEN|INFO|${reqList[$v]} OK!" t
-        fi
+        log "GEN|INFO|"${reqList[$v]}" version OK!" t
     fi
     ((v++))
 done
 
+if [[ $allGood > 0 ]]; then
+    for r in ${badVer[@]}; do
+        log "GEN|ERROR|"$r t
+    done
+    log "GEN|FATAL|Requirement are not met, please fix before continuing." t
+    return 1
+fi
+
 MYSH=$(readlink -f /bin/sh)
 echo "/bin/sh -> $MYSH"
-echo $MYSH | grep -q bash || log "GEN|ERROR|ERROR: /bin/sh does not point to bash"
+echo $MYSH | grep -q bash || log "GEN|ERROR|ERROR: /bin/sh does not point to bash" t
 unset MYSH
+return 1
 
 
 
@@ -94,3 +108,7 @@ else
     log "GEN|ERROR|g++ compilation failed"
 fi
 processCmd "rm -fv dummy.c dummy"
+
+log "GEN|INFO|If the requirements are good. Refer back to the manual: Building LFS in Stages." t
+log "GEN|INFO|Create your partition and file system and update pkm.conf." t
+
