bug fix, got a full run

diff --git a/etc/m4-1.4.18/config b/etc/m4-1.4.18/config
--- a/etc/m4-1.4.18/config
+++ b/etc/m4-1.4.18/config
@@ -1,5 +1,5 @@
 log "PKG|INFO|Apply some fixes." t
-processCmd "sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c"
+sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
 if [[ $? > 0 ]]; then
     log "PKG|ERROR|Error with sed." t
     return 1
@@ -8,6 +8,13 @@ fi
 echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
 if [[ $? > 0 ]]; then
     log "PKG|ERROR|Error with echo." t
+    return 1
+fi
+
+
+processCmd "./configure --prefix=/tools"
+if [[ $? > 0 ]]; then
+    log "PKG|ERROR|Error with configure." t
     return 1
 fi
 
