latest updates

diff --git a/etc/installPkm/depcheck b/etc/installPkm/depcheck
--- a/etc/installPkm/depcheck
+++ b/etc/installPkm/depcheck
@@ -3,8 +3,11 @@ pkmPath_=$LFS/opt/Pkm
 if [ ! -d $pkmPath_ ]; then
     processCmd "sudo install -vdm 0755 $pkmPath_"
     [ $? -gt 0 ] && log "GEN|ERROR|Error install $pkmPath_" t && return 1
-    
+else
+    processCmd "sudo rm -fr $pkmPath_/*"
+    [ $? -gt 0 ] && log "GEN|ERROR|Error removing old $pkgPath/*" t && return 1
 fi
+
 mPush $pkmPath_
 log "GEN|INFO|Downloading Pkm." t
 processCmd "sudo wget https://github.com/ericsimard52/lfs_pkm/archive/master.zip"
@@ -22,25 +25,5 @@ processCmd "sudo rm -v master.zip"
 processCmd "sudo cp -vfr $pkmPath_/Pkm/FAKEROOT/* $LFS/"
 [ $? -gt 0 ] && log "GEN|ERROR|Error copying pkm in system files." t && mPop && return 1
 mPop
-
-log "GEN|INFO|Creating needed symlink" t
-sudo chroot "$LFS" /tools/bin/env -i \
-     HOME=/root                  \
-     TERM="$TERM"                \
-     PS1='(lfs chroot) \u:\w\$ ' \
-     PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
-     /tools/bin/bash /usr/bin/pkmFirstRun.sh
-if [ $? -gt 0 ]; then
-    log "ERR|FATAL|Error during pkmFirstRun.sh Check your temporary tool chain to make sure all directory and links are there." t
-    return 1
-fi
-
-log "GEN|INFO|Removing pkmFirstRun.sh"
-processCmd "sudo rm -v $LFS/usr/bin/pkmFirstRun.sh"
-if [ $? -gt 0 ]; then
-    log "ERR|ERROR|Error removing pkmFirstRun.sh from lfs chroot environment."t
-fi
-
-log "GEN|INFO|It is now safe to remove the lfs user. Inside your original user home directory, you should still have lfsScripted. Adjust the script enterLfs.sh and run it to chroot into your temp lfs toolchain." t
 
 return 0
