Code cleanup, separated multipass source script

diff --git a/etc/bash-4.4.18/compile b/etc/bash-4.4.18/compile
--- a/etc/bash-4.4.18/compile
+++ b/etc/bash-4.4.18/compile
@@ -1,6 +1,2 @@
 processCmd "make"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with make." t
-    return 1
-fi
-return 0
+[ $? -gt 0 ] log "{PKG,ERR}|ERROR|Error with make." t && return 1 || return 0
diff --git a/etc/bash-4.4.18/config b/etc/bash-4.4.18/config
--- a/etc/bash-4.4.18/config
+++ b/etc/bash-4.4.18/config
@@ -1,6 +1,2 @@
 processCmd "./configure --prefix=/tools --without-bash-malloc"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
-return 0
+[ $? -gt 0 ] log "PKG|ERROR|Error with configure." t && return 1 || return 0
diff --git a/etc/bash-4.4.18/install b/etc/bash-4.4.18/install
--- a/etc/bash-4.4.18/install
+++ b/etc/bash-4.4.18/install
@@ -1,12 +1,6 @@
 processCmd "make install"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with install." t
-    return 1
-fi
+[ $? -gt 0 ] && log "{PKG,ERR}|ERROR|Error with install. Aborting!" t && return 1
+
 log "PKG|INFO|Linking."
 processCmd "ln -sv bash /tools/bin/sh"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with linking." t
-    return 1
-fi
-return 0
+[ $? -gt 0 ] && log "{PKG,ERR}|ERROR|Error with linking. Aborting!" t && return 1 || return 0
diff --git a/etc/coreutils-8.30/compile b/etc/coreutils-8.30/compile
--- a/etc/coreutils-8.30/compile
+++ b/etc/coreutils-8.30/compile
@@ -1,6 +1,3 @@
 processCmd "make"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with make." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with make." t && return 1
 return 0
diff --git a/etc/coreutils-8.30/config b/etc/coreutils-8.30/config
--- a/etc/coreutils-8.30/config
+++ b/etc/coreutils-8.30/config
@@ -1,6 +1,3 @@
 processCmd "./configure --prefix=/tools --enable-install-program=hostname"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 return 0
diff --git a/etc/expect-5.45.4/config b/etc/expect-5.45.4/config
--- a/etc/expect-5.45.4/config
+++ b/etc/expect-5.45.4/config
@@ -1,23 +1,16 @@
 log "PKG|INFO|Making backup of configure." t
-cp -v configure{,.orig}
-if [[ $? > 0 ]]; then
-  log "PKG|ERROR|Error cp config." t
-  return 1
-fi
+processCmd "cp -v configure{,.orig}"
+[ $? -gt 0 ] && log "PKG|ERROR|Error cp config." t && return 1
+
 
 log "PKG|INFO|Forcing Expect's configure script to use /bin/stty." t
 sed 's:/usr/local/bin:/bin:' configure.orig > configure
-if [[ $? > 0 ]]; then
-  log "PKG|ERROR|Error with sed." t
-  return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with sed." t && return 1
+
 
 log "PKG|INFO|Configure package." t
 processCmd "./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include"
-if [[ $? > 0 ]]; then
-  log "PKG|ERROR|Error with configure." t
-  return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 
 return 0
 
diff --git a/etc/expect-5.45.4/install b/etc/expect-5.45.4/install
--- a/etc/expect-5.45.4/install
+++ b/etc/expect-5.45.4/install
@@ -1,6 +1,3 @@
 make SCRIPTS="" install
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with install." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with install." t && return 1
 return 0
diff --git a/etc/findutils-4.6.0/config b/etc/findutils-4.6.0/config
--- a/etc/findutils-4.6.0/config
+++ b/etc/findutils-4.6.0/config
@@ -1,26 +1,15 @@
 log "PKG|INFO|Some fixes required by glibc"
 sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' gl/lib/*.c
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with first sed." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with first sed." t && return 1
 
 sed -i '/unistd/a #include <sys/sysmacros.h>' gl/lib/mountlist.c
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with second sed." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with second sed." t && return 1
+
 
 echo "#define _IO_IN_BACKUP 0x100" >> gl/lib/stdio-impl.h
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with first echo." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with first echo." t && return 1
 
 processCmd "./configure --prefix=/tools"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with first configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with first configure." t && return 1
 
 return 0
diff --git a/etc/gawk-4.2.1/config b/etc/gawk-4.2.1/config
--- a/etc/gawk-4.2.1/config
+++ b/etc/gawk-4.2.1/config
@@ -1,6 +1,3 @@
 processCmd "./configure --prefix=/tools"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with first configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with first configure." t && return 1
 return 0
diff --git a/etc/gettext-0.19.8.1/compile b/etc/gettext-0.19.8.1/compile
--- a/etc/gettext-0.19.8.1/compile
+++ b/etc/gettext-0.19.8.1/compile
@@ -1,36 +1,18 @@
-pushd gettext-tools > /dev/null
+mPush gettext-tools
 processCmd "make -C gnulib-lib"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with gnulib-lib" t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with gnulib-lib" t && mPop && return 1
+
 processCmd "make -C intl pluralx.c"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with intl pluralx.c" t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with intl pluralx.c" t && mPop && return 1
 
 processCmd "make -C src msgfmt"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with src msgfmt" t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with src msgfmt" t && mPop && return 1
 
 processCmd "make -C src msgmerge"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with src msgmerge" t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with src msgmerge" t && mPop && return 1
 
 processCmd "make -C src xgettext"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with src xgettext" t
-    popd > /dev/null
-    return 1
-fi
-popd > /dev/null
+[ $? -gt 0 ] && log "PKG|ERROR|Error with src xgettext" t && mPop && return 1
+
+mPop
 return 0
diff --git a/etc/gettext-0.19.8.1/config b/etc/gettext-0.19.8.1/config
--- a/etc/gettext-0.19.8.1/config
+++ b/etc/gettext-0.19.8.1/config
@@ -1,10 +1,7 @@
-pushd gettext-tools >/dev/null
+mPush gettext-tools
 EMACS="no" ./configure --prefix=/tools --disable-shared
 
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    popd > /dev/null
-    return 1
-fi
-popd > /dev/null
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && mPop && return 1
+
+mPop
 return 0
diff --git a/etc/gettext-0.19.8.1/install b/etc/gettext-0.19.8.1/install
--- a/etc/gettext-0.19.8.1/install
+++ b/etc/gettext-0.19.8.1/install
@@ -1,9 +1,5 @@
-pushd gettext-tools >/dev/null
+mPush gettext-tools
 cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with install." t
-    popd > /dev/null
-    return 1
-fi
-popd > /dev/null
+[ $? -gt 0 ] && log "PKG|ERROR|Error with install." t && mPop && return 1
+mPop
 return 0
diff --git a/etc/libstdc-8.2.0/config b/etc/libstdc-8.2.0/config
--- a/etc/libstdc-8.2.0/config
+++ b/etc/libstdc-8.2.0/config
@@ -1,6 +1,3 @@
 processCmd "../libstdc++-v3/configure --host=$LFS_TGT --prefix=/tools --disable-multilib --disable-nls --disable-libstdcxx-threads --disable-libstdcxx-pch --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/8.2.0"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error in config" t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error in config" t && return 1
 return 0
diff --git a/etc/libstdc-8.2.0/install b/etc/libstdc-8.2.0/install
--- a/etc/libstdc-8.2.0/install
+++ b/etc/libstdc-8.2.0/install
@@ -1,8 +1,5 @@
 processCmd "make install"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error installing." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error installing." t && return 1
 return 0
 
 
diff --git a/etc/linux-4.18.5/install b/etc/linux-4.18.5/install
--- a/etc/linux-4.18.5/install
+++ b/etc/linux-4.18.5/install
@@ -1,11 +1,6 @@
 processCmd "make INSTALL_HDR_PATH=dest headers_install"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error in make install" t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error in make install" t && return 1
+
 processCmd "cp -rv dest/include/* /tools/include"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error in cp" t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error in cp" t && return 1
 return 0
diff --git a/etc/m4-1.4.18/config b/etc/m4-1.4.18/config
--- a/etc/m4-1.4.18/config
+++ b/etc/m4-1.4.18/config
@@ -1,21 +1,11 @@
 log "PKG|INFO|Apply some fixes." t
 sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with sed." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with sed." t && return 1
 
 echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with echo." t
-    return 1
-fi
-
+[ $? -gt 0 ] && log "PKG|ERROR|Error with echo." t && return 1
 
 processCmd "./configure --prefix=/tools"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 
 return 0
diff --git a/etc/make-4.2.1/config b/etc/make-4.2.1/config
--- a/etc/make-4.2.1/config
+++ b/etc/make-4.2.1/config
@@ -1,12 +1,7 @@
 log "PKG|INFO|Implement work around an error caused by glibc" t
 sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with sed." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with sed." t && return 1
+
 processCmd "./configure --prefix=/tools --without-guile"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 return 0
diff --git a/etc/ncurses-6.1/config b/etc/ncurses-6.1/config
--- a/etc/ncurses-6.1/config
+++ b/etc/ncurses-6.1/config
@@ -1,14 +1,8 @@
 log "PKG|INFO|Ensure gawk is found during compilation"
 processCmd "sed -i s/mawk// configure"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with sed." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with sed." t && return 1
 
 log "PKG|INFO|Configuring." t
 processCmd "./configure --prefix=/tools --with-shared --without-debug --without-ada --enable-widec --enable-overwrite"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 return 0
diff --git a/etc/perl-5.28.0/config b/etc/perl-5.28.0/config
--- a/etc/perl-5.28.0/config
+++ b/etc/perl-5.28.0/config
@@ -1,6 +1,3 @@
 sh Configure -des -Dprefix=/tools -Dlibs=-lm -Uloclibpth -Ulocincpth
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 return 0
diff --git a/etc/perl-5.28.0/install b/etc/perl-5.28.0/install
--- a/etc/perl-5.28.0/install
+++ b/etc/perl-5.28.0/install
@@ -1,18 +1,9 @@
 processCmd "cp -v perl cpan/podlators/scripts/pod2man /tools/bin"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with task 1." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with task 1." t && return 1
 
 processCmd "mkdir -pv /tools/lib/perl5/5.28.0"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with task 2." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with task 2." t && return 1
 
 processCmd "cp -Rv lib/* /tools/lib/perl5/5.28.0"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with task 3." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with task 3." t && return 1
 return 0
diff --git a/etc/tcl-8.6.8/compile b/etc/tcl-8.6.8/compile
--- a/etc/tcl-8.6.8/compile
+++ b/etc/tcl-8.6.8/compile
@@ -1,9 +1,5 @@
-pushd unix >/dev/null
+mPush unix
 processCmd "make"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error in compile." t
-    popd >/dev/null
-    return 1
-fi
-popd >/dev/null
+[ $? -gt 0 ] && log "PKG|ERROR|Error in compile." t && mPop && return 1
+
 return 0
diff --git a/etc/tcl-8.6.8/config b/etc/tcl-8.6.8/config
--- a/etc/tcl-8.6.8/config
+++ b/etc/tcl-8.6.8/config
@@ -1,9 +1,6 @@
-pushd unix > /dev/null
+mPush unix
 processCmd "./configure --prefix=/tools"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with config." t
-    popd >/dev/null
-    return 1
-fi
-popd > /dev/null
+[ $? -gt 0 ] && log "PKG|ERROR|Error with config." t && mPop && return 1
+
+mPop
 return 0
diff --git a/etc/tcl-8.6.8/install b/etc/tcl-8.6.8/install
--- a/etc/tcl-8.6.8/install
+++ b/etc/tcl-8.6.8/install
@@ -1,35 +1,18 @@
-pushd unix >/dev/null
+mPush unix
 processCmd "make install"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with install." t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with install." t && mPop && return 1
 
 log "PKG|INFO|Making libraries writable." t
 processCmd "chmod -v u+w /tools/lib/libtcl8.6.so"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error making libraries writable." t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error making libraries writable." t && mPop && return 1
 
 log "PKG|INFO|Installing tcl's headers." t
 processCmd "make install-private-headers"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error installing." t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error installing." t && mPop && return 1
 
 log "PKG|INFO|Creating needed links." t
 processCmd "ln -sv tclsh8.6 /tools/bin/tclsh"
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error linking." t
-    popd > /dev/null
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error linking." t && mPop && return 1
 
-
-popd > /dev/null
+mPop
 return 0
diff --git a/etc/util-linux-2.32.1/config b/etc/util-linux-2.32.1/config
--- a/etc/util-linux-2.32.1/config
+++ b/etc/util-linux-2.32.1/config
@@ -1,6 +1,3 @@
 processCmd "./configure --prefix=/tools --without-python --disable-makeinstall-chown --without-systemdsystemunitdir --without-ncurses PKG_CONFIG=\"\""
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error with configure." t
-    return 1
-fi
+[ $? -gt 0 ] && log "PKG|ERROR|Error with configure." t && return 1
 return 0
