bug fix and finish first draft of source scripts.

diff --git a/etc/binutils-2.31.1/compile b/etc/binutils-2.31.1/compile
--- a/etc/binutils-2.31.1/compile
+++ b/etc/binutils-2.31.1/compile
@@ -9,13 +9,31 @@ function compilePass1 {
     case $(uname -m) in
         x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
     esac
+    return 0
 }
 
-promptUser "Which pass [1]"
+function compilePass2 {
+    processCmd "make"
+
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error processing make" t
+        return 1
+    fi
+    return 0
+}
+
+promptUser "Which pass [1,2]"
 read pass
 case $pass in
     1)
         compilePass1
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error withing compile source scripts." t
+            return 1
+        fi
+        ;;
+    2)
+        compilePass2
         if [[ $? > 0 ]]; then
             log "PKG|ERROR|Error withing compile source scripts." t
             return 1
@@ -26,3 +44,5 @@ case $pass in
         return 1
         ;;
 esac
+return 0
+
diff --git a/etc/binutils-2.31.1/config b/etc/binutils-2.31.1/config
--- a/etc/binutils-2.31.1/config
+++ b/etc/binutils-2.31.1/config
@@ -4,16 +4,34 @@ function configPass1 {
         log "PKG|ERROR|Error in configPass1.";
         return 1
     fi
+    return 0
+}
+function configPass2 {
+    CC=$LFS_TGT-gcc AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib ../configure --prefix=/tools --disable-nls --disable-werror --with-lib-path=/tools/lib --with-sysroot
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error in configPass2.";
+        return 1
+    fi
+    return 0
 }
 
 
-promptUser "Which pass [1]"
+promptUser "Which pass [1,2]"
 read pass
 
 
 case $pass in
     1)
         configPass1
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        ;;
+    2)
+        configPass2
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
         ;;
     *)
         log "{GEN,PKG,ERR}|ERROR|Choosed invalid pass." t t
@@ -21,4 +39,5 @@ case $pass in
         ;;
 esac
 
+return 0
 
diff --git a/etc/binutils-2.31.1/install b/etc/binutils-2.31.1/install
--- a/etc/binutils-2.31.1/install
+++ b/etc/binutils-2.31.1/install
@@ -1,2 +1,57 @@
-processCmd "make install"
-  
+function installPass1 {
+    processCmd "make install"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error installing." t
+        return 1
+    fi
+    return 0
+}
+
+function installPass2 {
+    processCmd "make install"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error installing." t
+        return 1
+    fi
+    processCmd "make -C ld clean"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error with make -C ld clean." t
+        return 1
+    fi
+    processCmd "make -C ld LIB_PATH=/usr/lib:/lib"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error with make -C ld LIB_PATH=/usr/lib:/lib." t
+        return 1
+    fi
+    processCmd "cp -v ld/ld-new /tools/bin"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error with cp -v ld/ld-new /tool/bin." t
+        return 1
+    fi
+    return 0
+}
+promptUser "Which pass [1,2]"
+read pass
+
+
+case $pass in
+    1)
+        installPass1
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        ;;
+    2)
+        installPass2
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        ;;
+    *)
+        log "{GEN,PKG,ERR}|ERROR|Choosed invalid pass." t t
+        return 1
+        ;;
+esac
+
+return 0
+
diff --git a/etc/gcc-8.2.0/check b/etc/gcc-8.2.0/check
--- a/etc/gcc-8.2.0/check
+++ b/etc/gcc-8.2.0/check
@@ -1,5 +1,53 @@
-ulimit -s 32768
-rm -v ../gcc/testsuite/g++.dg/pr83239.C
-chown -Rv nobody . 
-su nobody -s /bin/bash -c "PATH=$PATH make -k check"
-../contrib/test_summary | grep -A7 Summ
+function checkPass1 {
+    echo 'int main(){}' > dummy.c
+    $LFS_TGT-gcc dummy.c
+    readelf -l a.out | grep ': /tools'
+    promptUser "Looks good? [Yn]"
+    read c
+    case $c in
+        [nN])
+            log "PKG|ERROR|User reported error." t
+            processCmd "rm -v dummy.c a.out"
+            return 1
+    esac
+    processCmd "rm -v dummy.c a.out"
+    return 0
+}
+
+function checkPass2 {
+    echo 'int main(){}' > dummy.c
+    cc dummy.c
+    readelf -l a.out | grep ': /tools'
+    promptUser "Looks good? [Yn]"
+    read c
+    case $c in
+        [nN])
+            log "PKG|ERROR|User reported error." t
+            processCmd "rm -v dummy.c a.out"
+            return 1
+    esac
+    processCmd "rm -v dummy.c a.out"
+    return 0
+}
+
+promptUser "Which pass [1,2]"
+read c
+case $c in
+    1)
+        checkPass1
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        return 0
+        ;;
+    2)
+        checkPass2
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        return 0
+        ;;
+    *)
+        log "PKG|WARNING|Invalid option." t
+        return 1
+esac
diff --git a/etc/gcc-8.2.0/compile b/etc/gcc-8.2.0/compile
--- a/etc/gcc-8.2.0/compile
+++ b/etc/gcc-8.2.0/compile
@@ -6,7 +6,14 @@ function compilePass1 {
         return 1
     fi
 }
-promptUser "Which pass [1]"
+function compilePass2 {
+    processCmd "make"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error compiling pass 2." t
+        return 1
+    fi
+}
+promptUser "Which pass [1,2]"
 read pass
 case $pass in
     1)
@@ -15,10 +22,17 @@ case $pass in
             log "PKG|ERROR|Error withing compile source scripts." t
             return 1
         fi
-
+        ;;
+    2)
+        compilePass2
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error withing compile source scripts." t
+            return 1
+        fi
         ;;
     *)
         log "PKG|ERROR|Invalid option."
         return 1
         ;;
 esac
+return 0
diff --git a/etc/gcc-8.2.0/config b/etc/gcc-8.2.0/config
--- a/etc/gcc-8.2.0/config
+++ b/etc/gcc-8.2.0/config
@@ -5,16 +5,37 @@ function configPass1 {
         log "PKG|ERROR|Error configure pass 1" t
         return 1
     fi
+    return 0
 }
 
-promptUser "Which pass [1]"
+function configPass2 {
+    processCmd "CC=$LFS_TGT-gcc CXX=$LFS_TGT-g++ AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib ../configure --prefix=/tools --with-local-prefix=/tools --with-native-system-header-dir=/tools/include --enable-languages=c,c++ --disable-libstdcxx-pch --disable-multilib --disable-bootstrap --disable-libgomp"
+
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error configure pass 2" t
+        return 1
+    fi
+    return 0
+}
+
+promptUser "Which pass [1,2]"
 read pass
 case $pass in
     1)
         configPass1
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
+        ;;
+    2)
+        configPass2
+        if [[ $? > 0 ]]; then
+            return 1
+        fi
         ;;
     *)
         log "PKG|ERROR|Invalid option."
         return 1
         ;;
 esac
+return 0
diff --git a/etc/gcc-8.2.0/install b/etc/gcc-8.2.0/install
--- a/etc/gcc-8.2.0/install
+++ b/etc/gcc-8.2.0/install
@@ -4,13 +4,37 @@ function installPass1 {
         log "PKG|ERROR|Error install pass 1" t
         return 1
     fi
+    return 0
 }
 
-promptUser "Which pass [1]"
+function installPass2 {
+    processCmd "make install"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error install pass 2" t
+        return 1
+    fi
+
+    log "PKG|INFO|Linking gcc to /tools/bin/cc" t
+    processCmd "ln -sv gcc /tools/bin/cc"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error in linking." t
+        return 1
+    fi
+    return 0
+}
+
+promptUser "Which pass [1,2]"
 read pass
 case $pass in
     1)
         installPass1
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error withing install source scripts." t
+            return 1
+        fi
+        ;;
+    2)
+        installPass2
         if [[ $? > 0 ]]; then
             log "PKG|ERROR|Error withing install source scripts." t
             return 1
@@ -22,3 +46,4 @@ case $pass in
         ;;
 esac
 
+return 0
diff --git a/etc/gcc-8.2.0/preconfig b/etc/gcc-8.2.0/preconfig
--- a/etc/gcc-8.2.0/preconfig
+++ b/etc/gcc-8.2.0/preconfig
@@ -52,16 +52,115 @@ function preConfigPass1 {
             ;;
     esac
 
+    return 0
+
 }
 
-promptUser "Which pass [1]"
+function preConfigPass2 {
+    log "PKG|INFO|Create a full version of the internal header." t
+    cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
+        `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h
+    if [[ $? > 0 ]]; then
+        log "PKG|ERRPR|Error in preconfigPass2." t
+        return 1
+    fi
+
+    log "PKG|INFO|Changing the location of GCC's default dynamic linker." t
+    for file in gcc/config/{linux,i386/linux{,64}}.h
+    do
+        cp -uv $file{,.orig}
+        sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
+            -e 's@/usr@/tools@g' $file.orig > $file
+        echo '
+        #undef STANDARD_STARTFILE_PREFIX_1
+        #undef STANDARD_STARTFILE_PREFIX_2
+        #define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
+        #define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
+        touch $file.orig
+    done
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Something seems wrong." t
+        return 1
+    fi
+
+    log "PKG|INFO|Adjusting if x64 system." t
+    case $(uname -m) in
+        x86_64)
+            sed -e '/m64=/s/lib64/lib/' \
+                -i.orig gcc/config/i386/t-linux64
+            ;;
+    esac
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Something is wrond." t
+        return 1
+    fi
+
+    promptUser "Do we continue? [Yn]?"
+    read c
+    case $c in
+        [nN])
+            log "PKG|ERROR|User reported error." t
+            return 1
+            ;;
+    esac
+
+    log "PKG|INFO|Unpacking extra packages." t
+    processCmd "tar -xf ../mpfr-4.0.1.tar.xz"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error unpacking mpfr" t
+        return 1
+    fi
+    processCmd "mv -v mpfr-4.0.1 mpfr"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error moving mpfr" t
+        return 1
+    fi
+    processCmd "tar -xf ../gmp-6.1.2.tar.xz"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error unpacking gmp" t
+        return 1
+    fi
+    processCmd "mv -v gmp-6.1.2 gmp"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error moving gmp" t
+        return 1
+    fi
+
+    processCmd "tar -xf ../mpc-1.1.0.tar.gz"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error unpacking mpc" t
+        return 1
+    fi
+    processCmd "mv -v mpc-1.1.0 mpc"
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error moving gmp" t
+        return 1
+    fi
+
+    log "PKG|INFO|Done." t
+    return 0
+}
+
+promptUser "Which pass [1,2]"
 read pass
 case $pass in
     1)
         preConfigPass1
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error config pass 1." t
+            return 1
+        fi
+        ;;
+    2)
+        preConfigPass2
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error config pass 2." t
+            return 1
+        fi
         ;;
     *)
         log "PKG|ERROR|Invalid option."
         return 1
         ;;
 esac
+return 0
