update to pkm.sh

diff --git a/etc/binutils-2.31.1/compile b/etc/binutils-2.31.1/compile
--- a/etc/binutils-2.31.1/compile
+++ b/etc/binutils-2.31.1/compile
@@ -1,10 +1,28 @@
-processCmd "make"
+function compilePass1 {
+    processCmd "make"
 
-if [[ $? > 0 ]]; then
-    log "PKG|ERROR|Error processing make" t
-    return 1
-fi
+    if [[ $? > 0 ]]; then
+        log "PKG|ERROR|Error processing make" t
+        return 1
+    fi
 
-case $(uname -m) in
-  x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
+    case $(uname -m) in
+        x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
+    esac
+}
+
+promptUser "Which pass [1]"
+read pass
+case $pass in
+    1)
+        compilePass1
+        if [[ $? > 0 ]]; then
+            log "PKG|ERROR|Error withing compile source scripts." t
+            return 1
+        fi
+        ;;
+    *)
+        log "PKG|ERROR|Invalid option."
+        return 1
+        ;;
 esac
diff --git a/etc/versionCheck/depcheck b/etc/versionCheck/depcheck
--- a/etc/versionCheck/depcheck
+++ b/etc/versionCheck/depcheck
@@ -136,7 +136,18 @@ else
 fi
 
 echo 'int main(){}' > dummy.c && g++ -o dummy dummy.c
+if [[ $? > 0 ]]; then
+    log "GEN|ERROR|Unable to create dummy.c." t
+    curd=`cwd`
+    log "ERR|INFO|Current directory: $curd" t
+    return 1
+fi
 if [ -x dummy ];then
+    ./dummy
+    if [[ $? > 0 ]]; then
+        log "GEN|ERROR|Unable to execute dummy." t
+        return 1
+    fi
     log "GEN|INFO|g++ compilation OK" t
 else
     log "GEN|ERROR|g++ compilation failed"
