working on building tmp tool chains.

diff --git a/etc/pkm/tmpToolChain/binutils-2.31.1/compile b/etc/pkm/tmpToolChain/binutils-2.31.1/compile
--- a/etc/pkm/tmpToolChain/binutils-2.31.1/compile
+++ b/etc/pkm/tmpToolChain/binutils-2.31.1/compile
@@ -1,4 +1,26 @@
-eval "make"
-if [[ $? > 0 ]]; then
-  return 1
-fi
+function compilePass1 {
+    eval "make"
+    if [[ $? > 0 ]]; then
+        return 1
+    fi
+}
+function compilePass2 {
+    eval "make"
+    if [[ $? > 0 ]]; then
+        return 2
+    fi
+}
+
+promptUser "Which Pass? 1, 2"
+read u
+case $u in
+    1)
+        compilePass1
+        ;;
+    2)
+        compilePass2
+        ;;
+    *)
+        log "ERROR: Unknown choice."
+        ;;
+esac
diff --git a/etc/pkm/tmpToolChain/binutils-2.31.1/install b/etc/pkm/tmpToolChain/binutils-2.31.1/install
--- a/etc/pkm/tmpToolChain/binutils-2.31.1/install
+++ b/etc/pkm/tmpToolChain/binutils-2.31.1/install
@@ -1,4 +1,26 @@
-eval "make install"
-if [[ $? > 0 ]]; then
-  return 1
-fi
+function installPass1 {
+    eval "make install"
+    if [[ $? > 0 ]]; then
+        return 1
+    fi
+}
+function installPass2 {
+    eval "make install"
+    if [[ $? > 0 ]]; then
+        return 2
+    fi
+}
+
+promptUser "Which Pass? 1, 2"
+read u
+case $u in
+    1)
+        installPass1
+        ;;
+    2)
+        installPass2
+        ;;
+    *)
+        log "ERROR: Unknown choice."
+        ;;
+esac
